### ISSUE TITLE
Blocks .docx .xldx .pptx etc

### ISSUE THREAD

**Issue by peavers** [silverstripe/silverstripe-mimevalidator#1]
If this module exists on 3.1.6 whether it is configured or not (via config.yml), it rejects all the newer MS Office file types.

As soon as this module is deleted all file types work again. Only error give when trying to upload is "Forbidden". I don't see anything in the documentation around needing to allow basic file types, nor at a glance do I see anything in the code that should be blocking them? 

Replicable on the 1.0.4 CWP recipe and a standard base install.

**Comment by robbieaverill** [comment]
Should be fixed now, feel free to reopen if it's still a problem in more recent versions
