### ISSUE TITLE
Check and update module for SS4 compatibility where necessary

### ISSUE THREAD

**Issue by rupachup** [silverstripe/silverstripe-mimevalidator#28]
## Sub Tasks

- [x] Make VendorModule
- [x] Ensure all CI support is up to date
- [x] Ensure tests pass
- [x] Check module works as expected
- [x] Check no other deprecated code still in the module
- [x] Remove `.tx` folder from 1.0 branch, merge up to master (without removing from master)
- [x] Push new translations to Transifex

## Pull requests

- [x] #29 
- [x] #30

**Comment by NightJar** [comment]
Bulk of the work done in #29

**Comment by robbieaverill** [comment]
Nice work! https://github.com/silverstripe/silverstripe-mimevalidator/releases/tag/2.0.0-beta1
