### ISSUE TITLE
Array merging issue when custom mime-type is specified via HTTP class config

### ISSUE THREAD

**Issue by michalkleiner** [silverstripe/silverstripe-mimevalidator#31]
When a custom mime-type is specified in the config on the HTTP class as outlined in https://github.com/silverstripe/cwp/blob/1.5/docs/en/03_How_tos/adding_an_allowed_extension.md#adding-an-allowed-extension-for-file-upload, the array merging using the addition as per https://github.com/silverstripe/silverstripe-mimevalidator/blob/1.0/code/MimeUploadValidator.php#L92 overwrites the first specified mime-type instead of adding to the list.

This issue only appears in the 1.0 branch, it's fixed in latest master (from version 2).

**Comment by robbieaverill** [comment]
Are you keen to back port a fix for this into 1.0 @michalkleiner?

**Comment by michalkleiner** [comment]
Here you go @robbieaverill - #32

**Comment by michalkleiner** [comment]
If you merge this, can you also tag it? Thanks.

**Comment by robbieaverill** [comment]
Done: https://github.com/silverstripe/silverstripe-mimevalidator/compare/1.0.11...1.0.12

Cheers!
