### ISSUE TITLE
Rephrase error messages

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-mimevalidator#33]
Currently "File does not match MIME type" doesn't mean much to the average user. It's a tricky one to phrase because "file extensions" aren't generally a well known concept either.

Also unsure at this point is whether this is simply translation based, but in any case we _can_ update the default string for a translation, which is in the code.

**Comment by robbieaverill** [comment]
@NightJar can you triage this for the version affecting you? I assume it's probably both SS3 and SS4

**Comment by NightJar** [comment]
Hmm, I haven't done my due dilligence with this issue (didn't link related). I _think_ it was related to https://github.com/silverstripe/silverstripe-asset-admin/issues/708 which has since been solved, so should probably be checked to see if this is still a thing.

**Comment by NightJar** [comment]
Cool, so the customised error message now displays, thanks to UncleCheese's fix.
But the UX portion of this issue with regards to the error message itself is still in need of addressing. Attached is a screenshot as requested by @sachajudd :)

![capture](https://user-images.githubusercontent.com/778003/34965610-3f78c1ec-faba-11e7-82d4-5c43dc85cae1.PNG)

**Comment by clarkepaul** [comment]
"Unknown file type (MIME)" would make more sense but why is a PNG not being allowed here?

**Comment by NightJar** [comment]
I think this is more in reference to the general concept of a MIME type not being something the average user is aware of. Such as you providing a perfect example in your comment @clarkepaul (not sure if that's intentional or not) - the PNG isn't a png. It's a text file (see second window in screenshot, just below the upload field).

Something like "File doesn't appear to be what it says it is" (although clearly that's also a bit rubbish) might be better.

**Comment by clarkepaul** [comment]
"File extension and type is not supported or recognised"?

**Comment by NightJar** [comment]
"File type does not match extension ($EXT)"
e.g. (using the same example) `File type does not match extension (.PNG)`?

**Comment by clarkepaul** [comment]
Yup good :)
